server:
  port: 8001
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      url: jdbc:mysql://localhost:3306/dynaDataBases?characterEncoding=utf8&useSSL=false&autoReconnect=true
      username: root
      password: 123456
    slave:
      url: jdbc:mysql://localhost:3307/dynaDataBases?characterEncoding=utf8&useSSL=false&autoReconnect=true
      username: root
      password: 123456
mybatis:
  database:
    type: mysql
  model:
    pack: com.domin
  table:
    auto: update


